/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

/**
 *
 * @author TOSHIBA SATELLITE
 */
public class VentanaPuntajes extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPuntajes
     */
    public VentanaPuntajes() {
        initComponents();
        this.Jugadorestxr.setText(Pong.puntajes.jugadores[0].getNombre());
        this.puntajetxt.setText(Integer.toString(Pong.puntajes.jugadores[0].getPuntaje()));
        
        this.Jugadorestxr1.setText(Pong.puntajes.jugadores[1].getNombre());
        this.puntajetxt1.setText(Integer.toString(Pong.puntajes.jugadores[1].getPuntaje()));
        
        this.Jugadorestxr2.setText(Pong.puntajes.jugadores[2].getNombre());
        this.puntajetxt2.setText(Integer.toString(Pong.puntajes.jugadores[2].getPuntaje()));
        
        this.Jugadorestxr3.setText(Pong.puntajes.jugadores[3].getNombre());
        this.puntajetxt3.setText(Integer.toString(Pong.puntajes.jugadores[3].getPuntaje()));
        
        this.Jugadorestxr4.setText(Pong.puntajes.jugadores[4].getNombre());
        this.puntajetxt4.setText(Integer.toString(Pong.puntajes.jugadores[4].getPuntaje()));
        
        this.Jugadorestxr5.setText(Pong.puntajes.jugadores[5].getNombre());
        this.puntajetxt5.setText(Integer.toString(Pong.puntajes.jugadores[5].getPuntaje()));
        
        this.Jugadorestxr6.setText(Pong.puntajes.jugadores[6].getNombre());
        this.puntajetxt6.setText(Integer.toString(Pong.puntajes.jugadores[6].getPuntaje()));
        
        this.Jugadorestxr7.setText(Pong.puntajes.jugadores[7].getNombre());
        this.puntajetxt7.setText(Integer.toString(Pong.puntajes.jugadores[7].getPuntaje()));
        
        this.Jugadorestxr8.setText(Pong.puntajes.jugadores[8].getNombre());
        this.puntajetxt8.setText(Integer.toString(Pong.puntajes.jugadores[8].getPuntaje()));
        
        this.Jugadorestxr9.setText(Pong.puntajes.jugadores[9].getNombre());
        this.puntajetxt9.setText(Integer.toString(Pong.puntajes.jugadores[9].getPuntaje()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        puntajetxt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Jugadorestxr = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Jugadorestxr1 = new javax.swing.JLabel();
        puntajetxt1 = new javax.swing.JLabel();
        Jugadorestxr2 = new javax.swing.JLabel();
        puntajetxt2 = new javax.swing.JLabel();
        puntajetxt3 = new javax.swing.JLabel();
        Jugadorestxr3 = new javax.swing.JLabel();
        Jugadorestxr4 = new javax.swing.JLabel();
        puntajetxt4 = new javax.swing.JLabel();
        Jugadorestxr5 = new javax.swing.JLabel();
        puntajetxt5 = new javax.swing.JLabel();
        puntajetxt6 = new javax.swing.JLabel();
        Jugadorestxr6 = new javax.swing.JLabel();
        Jugadorestxr7 = new javax.swing.JLabel();
        puntajetxt7 = new javax.swing.JLabel();
        puntajetxt8 = new javax.swing.JLabel();
        Jugadorestxr8 = new javax.swing.JLabel();
        Jugadorestxr9 = new javax.swing.JLabel();
        puntajetxt9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        puntajetxt.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        puntajetxt.setForeground(new java.awt.Color(255, 255, 255));
        puntajetxt.setText("Puntaje");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Puntajes");

        Jugadorestxr.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        Jugadorestxr.setForeground(new java.awt.Color(255, 255, 255));
        Jugadorestxr.setText("Jugadores");

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Jugadorestxr1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        Jugadorestxr1.setForeground(new java.awt.Color(255, 255, 255));
        Jugadorestxr1.setText("Jugadores");

        puntajetxt1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        puntajetxt1.setForeground(new java.awt.Color(255, 255, 255));
        puntajetxt1.setText("Puntaje");

        Jugadorestxr2.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        Jugadorestxr2.setForeground(new java.awt.Color(255, 255, 255));
        Jugadorestxr2.setText("Jugadores");

        puntajetxt2.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        puntajetxt2.setForeground(new java.awt.Color(255, 255, 255));
        puntajetxt2.setText("Puntaje");

        puntajetxt3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        puntajetxt3.setForeground(new java.awt.Color(255, 255, 255));
        puntajetxt3.setText("Puntaje");

        Jugadorestxr3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        Jugadorestxr3.setForeground(new java.awt.Color(255, 255, 255));
        Jugadorestxr3.setText("Jugadores");

        Jugadorestxr4.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        Jugadorestxr4.setForeground(new java.awt.Color(255, 255, 255));
        Jugadorestxr4.setText("Jugadores");

        puntajetxt4.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        puntajetxt4.setForeground(new java.awt.Color(255, 255, 255));
        puntajetxt4.setText("Puntaje");

        Jugadorestxr5.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        Jugadorestxr5.setForeground(new java.awt.Color(255, 255, 255));
        Jugadorestxr5.setText("Jugadores");

        puntajetxt5.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        puntajetxt5.setForeground(new java.awt.Color(255, 255, 255));
        puntajetxt5.setText("Puntaje");

        puntajetxt6.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        puntajetxt6.setForeground(new java.awt.Color(255, 255, 255));
        puntajetxt6.setText("Puntaje");

        Jugadorestxr6.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        Jugadorestxr6.setForeground(new java.awt.Color(255, 255, 255));
        Jugadorestxr6.setText("Jugadores");

        Jugadorestxr7.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        Jugadorestxr7.setForeground(new java.awt.Color(255, 255, 255));
        Jugadorestxr7.setText("Jugadores");

        puntajetxt7.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        puntajetxt7.setForeground(new java.awt.Color(255, 255, 255));
        puntajetxt7.setText("Puntaje");

        puntajetxt8.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        puntajetxt8.setForeground(new java.awt.Color(255, 255, 255));
        puntajetxt8.setText("Puntaje");

        Jugadorestxr8.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        Jugadorestxr8.setForeground(new java.awt.Color(255, 255, 255));
        Jugadorestxr8.setText("Jugadores");

        Jugadorestxr9.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        Jugadorestxr9.setForeground(new java.awt.Color(255, 255, 255));
        Jugadorestxr9.setText("Jugadores");

        puntajetxt9.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        puntajetxt9.setForeground(new java.awt.Color(255, 255, 255));
        puntajetxt9.setText("Puntaje");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Jugadorestxr, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addComponent(puntajetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Jugadorestxr1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(puntajetxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Jugadorestxr2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(puntajetxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Jugadorestxr3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(puntajetxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Jugadorestxr4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(puntajetxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Jugadorestxr5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(puntajetxt5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Jugadorestxr6, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(puntajetxt6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Jugadorestxr7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(puntajetxt7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Jugadorestxr8, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(puntajetxt8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Jugadorestxr9, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(puntajetxt9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(137, 137, 137)
                    .addComponent(jLabel2)
                    .addContainerGap(137, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jugadorestxr)
                    .addComponent(puntajetxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jugadorestxr1)
                    .addComponent(puntajetxt1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jugadorestxr2)
                    .addComponent(puntajetxt2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jugadorestxr3)
                    .addComponent(puntajetxt3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jugadorestxr4)
                    .addComponent(puntajetxt4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jugadorestxr5)
                    .addComponent(puntajetxt5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jugadorestxr6)
                    .addComponent(puntajetxt6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jugadorestxr7)
                    .addComponent(puntajetxt7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jugadorestxr8)
                    .addComponent(puntajetxt8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jugadorestxr9)
                    .addComponent(puntajetxt9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel2)
                    .addContainerGap(313, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Inicio menu = new Inicio();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPuntajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPuntajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPuntajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPuntajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPuntajes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jugadorestxr;
    private javax.swing.JLabel Jugadorestxr1;
    private javax.swing.JLabel Jugadorestxr2;
    private javax.swing.JLabel Jugadorestxr3;
    private javax.swing.JLabel Jugadorestxr4;
    private javax.swing.JLabel Jugadorestxr5;
    private javax.swing.JLabel Jugadorestxr6;
    private javax.swing.JLabel Jugadorestxr7;
    private javax.swing.JLabel Jugadorestxr8;
    private javax.swing.JLabel Jugadorestxr9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel puntajetxt;
    private javax.swing.JLabel puntajetxt1;
    private javax.swing.JLabel puntajetxt2;
    private javax.swing.JLabel puntajetxt3;
    private javax.swing.JLabel puntajetxt4;
    private javax.swing.JLabel puntajetxt5;
    private javax.swing.JLabel puntajetxt6;
    private javax.swing.JLabel puntajetxt7;
    private javax.swing.JLabel puntajetxt8;
    private javax.swing.JLabel puntajetxt9;
    // End of variables declaration//GEN-END:variables
}
